### ISSUE TITLE
Can't confirm transaction with Ledger

### ISSUE THREAD

**Issue by iv41879** [zcoinofficial/electrum-xzc#21] opened 2019-02-22 20:25 UTC
Hi,

when trying to send coins I get stuck with message "Confirm Transaction on your Ledger device..." but nothing is appearing on my Ledger device within ZCoin application.
I have just uploaded to latest version of Electrum.

Thx

**Comment by yuri1313** [comment] 2019-03-03 17:14
Same issue here. Any update on this subject @a-bezrukov ?

**Comment by a-bezrukov** [comment] 2019-03-04 10:46
Hi Guys, 

I cannot reproduce the issue - I am sending txs successfully. As a general thought, I can only advice to upgrade your device firmware. If the issue persists, please provide more info - your OS version, console output (if any), relevant system log/error messages.

RSVP

**Comment by yuri1313** [comment] 2019-03-04 13:10
@a-bezrukov 
The Ledger is already running the latest firmware version (1.5.5). Already tried resetting and repairing the ledger. I installed the Bitcoin, Ethereum and ZCoin apps, nothing else.
OS Version: tried with Windows 10 build 1809 and Mac OS X 10.14.3.
Running the dmg builds on the mac and the installer on Windows. Let me know if there's anything I can do (such as running it in the console), to send you additional input.

**Comment by a-bezrukov** [comment] 2019-03-05 07:56
@yuri1313 
Let's try to gather some logs on macOS. 

1. Please download the latest release 3.3.4a2 and install the DMG 
2. Find the executable and launch it in verbose mode like this: /Volumes/Electrum-XZC/Electrum-XZC.app/Contents/MacOS/Electrum-XZC -v &>ledger.log 
3. Try sending a TX with your Nano S and close Electrum-XZC
4. Please make sure there is no private information in the ledger.log and send it to me. I've written a hello message to your e-mail fmp*****k.com

Regards

**Comment by yuri1313** [comment] 2019-03-05 09:43
hi Andrey,

I’ve attached the log (redacted my account addresses).
It’s throwing an exception at the end because I closed the app on my ledger after waiting a few minutes to see if anything popped up in the device’s screen.



Thanks!

On 5 Mar 2019, at 07:56, a-bezrukov <notifications@github.com<mailto:notifications@github.com>> wrote:


@yuri1313<https://github.com/yuri1313>
Let's try to gather some logs on macOS.

  1.  Please download the latest release 3.3.4a2 and install the DMG
  2.  Find the executable and launch it in verbose mode like this: /Volumes/Electrum-XZC/Electrum-XZC.app/Contents/MacOS/Electrum-XZC -v &>ledger.log
  3.  Try sending a TX with your Nano S and close Electrum-XZC
  4.  Please make sure there is no private information in the ledger.log and send it to me. I've written a hello message to your e-mail fmp*****k.com<http://k.com>

Regards

**Comment by a-bezrukov** [comment] 2019-03-06 15:16
Hi @yuri1313, @iv41879, 

Could you please check if your Nano S shows an address confirmation? Please launch Electrum-XZC, go to the View menu, choose Show Addresses. An "Addresses" tab should appear.  Right-click on any of the addresses and choose "Show on Ledger" item from the pop-up menu. Will your Nano S show a confirmation screen to you?

**Comment by riordant** [comment] 2019-03-07 10:16
@iv41879,
Please ensure that you are at at least each version of the following:
Ledger Device - 1.4.2
Zcoin app on Ledger Device - 1.2.9
Electrum XZC - 3.3.4a2

**Comment by yuri1313** [comment] 2019-03-08 00:10
@riordant @a-bezrukov . tested the "show on ledger" item, and it works as expected , so the issue seems to be only with the transaction signing feature.
Running:
Ledger nano s with firmware 1.5.5
Zcoin app on ledger device: 1.3.7
Electrum XZC: 3.3.4a2

**Comment by blondster** [comment] 2019-03-12 14:38
I myself have this problem - what should I do?
I need to get my quantity withdraws of my wallet now!

**Comment by a-bezrukov** [comment] 2019-03-12 14:57
@blondster what is your OS? What is the Elecrum-XZC version you generated your addresses with?

**Comment by blondster** [comment] 2019-03-12 15:18
Windows 7 64bit , installed now is Electrum xzc 3.3.4a2. Generated address on Electrum xzc 3.0.5a7

**Comment by a-bezrukov** [comment] 2019-03-12 15:48
@blondster Please downgrade for now while we solve the issue. In order to downgrade:
0. Please backup your wallet secret if any
1. Uninstall the Electrum-XZC
2. Delete the blockchain_headers file in the electrum-xzc data directory (del %UserProfile%\AppData\Roaming\Electrum-XZC\blockchain_headers)
3. Blacklist these 2 IP addresses in your Windows firewall: 45.63.90.6 and 45.76.92.160 (the upgraded electrumx servers)
4. Install the 3.0.5a7 version.

**Comment by blondster** [comment] 2019-03-12 15:52
Any solution for that moment?

**Comment by blondster** [comment] 2019-03-12 17:50
I did everything step by step, but now she writes that she can not open the wallet because it is an old version. I created a new wallet and now shows sync and I'm waiting to see it will sync.

**Comment by blondster** [comment] 2019-03-12 17:53
In manual mode which server to choose to sync?

**Comment by a-bezrukov** [comment] 2019-03-12 17:56
electrumx.zcoin.io, electrumx03.zcoin.io

**Comment by blondster** [comment] 2019-03-12 17:56
I chose this - electrumx02.zcoin.io, after a couple of restarts the program started syncing, but the transactions remain not verified.

**Comment by blondster** [comment] 2019-03-12 18:16
By choosing - electrumx.zcoin.io and electrumx01.zcoin.io - status is "not connect" , electrumx02.zcoin.io and electrumx03.zcoin.io - status is "synchronizing"  . Balance syncs one part, but not all. How long does it take to sync ?

**Comment by robin19741806** [comment] 2019-03-12 18:17
Здравствуйте! У меня тоже зависает на "Confirm Transaction on your Ledger device...", не могу подтвердить транзакцию.
Ledger nano s with firmware 1.5.5
Zcoin app on ledger device: 1.3.7
Electrum XZC: 3.3.4a2 Mac OS

**Comment by robin19741806** [comment] 2019-03-12 18:23
Hello! I also hang on the "Confirm Transaction on your Ledger device ...", I can not confirm the transaction.
Ledger nano s with firmware 1.5.5
Zcoin app on ledger device: 1.3.7
Electrum XZC: 3.3.4a2 Mac OS

**Comment by blondster** [comment] 2019-03-12 18:32
I tried all servers. The balance is not the same as before installing 3.0.5a7 . Sync. is 99% :) .

**Comment by a-bezrukov** [comment] 2019-03-12 18:42
@blondster Please do the following with your 3.0.5a7:
1.Stop your Electrum-XZC,  
2. Blacklist these 2 IP addresses in your Windows firewall: 45.63.90.6 and 45.76.92.160 (outbound connections by all programs on all ports)
3. Delete the blockchain_headers file in the electrum-xzc data directory (del %UserProfile%\AppData\Roaming\Electrum-XZC\blockchain_headers)
4. Connect to electrumx.zcoin.io or electrumx03.zcoin.io

**Comment by a-bezrukov** [comment] 2019-03-12 18:51
Before downgrading, please follow the manufacturers troubleshooting guide:  https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

**Comment by blondster** [comment] 2019-03-12 18:52
[https://drive.google.com/open?id=1GNEVFxaBclAa8QxWsFHy71XP7fnotx3a](url1)
[https://drive.google.com/open?id=1cEZXW1F_ebpb1jHR6OSgqT0ocOtymLVp](url2)
[https://drive.google.com/open?id=1gn9cpVadZpwiXc_zowzEyKcxYf-sy9rm](url3)
Status : synchronizing...

**Comment by a-bezrukov** [comment] 2019-03-12 19:03
@blondster Please accept my apologies, it should be 45.63.90.6 and 45.76.92.160. I edited the previous messages to not mislead other people

**Comment by blondster** [comment] 2019-03-12 19:12
Now - balance it's ok . Wallet is synchronized , but transactions is - not verified .  
[https://drive.google.com/open?id=1_otMC3nB6aP6x4LTk2YYPfASLCt72_hu](url)

The problem is the same ! :(

**Comment by a-bezrukov** [comment] 2019-03-12 19:19
@blondster I am sorry for that. We are working with Ledger to solve it. I cannot suggest anything but the official guide: https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues and try it on another computer
P.S. Your latest post contains your address. Please consider removing it to protect your privacy.

**Comment by blondster** [comment] 2019-03-12 19:26
I think I have no problem connecting to the ledger wallet , because by choosing the option in the electrum wallet to show me the address of the ledger wallet - it works . :(
I will now try another computer. Which version should I try 3.0.5a7 or 3.3.4a2 ?

**Comment by a-bezrukov** [comment] 2019-03-12 19:29
Please try 3.0.5a7 first. Blacklisting the IPs of the new electrumx servers will be needed still.

**Comment by ershuev** [comment] 2019-03-12 20:08
Hello! I have the same problem "Confirm Transaction on your Ledger device ..."
Windows 10 1809 (17763.379)
Ledger nano s with firmware 1.5.5
Zcoin app on ledger device: 1.3.7
have tried:
electrum-xzc-3.3.4a2-setup.exe
electrum-xzc-3.3.4a2-portable.exe
electrum-xzc-3.3.3a1-portable.exe
electrum-xzc-3.0.5a7-portable.exe

**Comment by blondster** [comment] 2019-03-12 20:30
I tried on another computer with windows 7 (electrum-xzc 3.0.5a7) and the problem is the same. 
Is there any other way to send the amount of currency ?
This problem cost me very expensive ... and the problem remains unresolved :(

**Comment by blondster** [comment] 2019-03-13 06:18
Good morning , 
Are there any problems with Linux ?

**Comment by a-bezrukov** [comment] 2019-03-13 06:29
I cannot reproduce the issue on either Linux, Mac or Windows. Whatever I do - resetting the device, sending BTC then closing Electrum and then instantly sending XZC - it all works for me on all 3 OSes. So I guess that the problem is unrelated to an OS. Please try it with a VM if you can.

**Comment by robin19741806** [comment] 2019-03-13 06:39
Running on the latest version electrum-xzc-3.3.4a2?

**Comment by robin19741806** [comment] 2019-03-13 06:43
I tried on all versions of mac os, windows, portable. Nowhere does it work!
electrum-xzc-3.0.5a5
electrum-xzc-3.0.5a6
electrum-xzc-3.0.5a7
electrum-xzc-3.3.3a1
electrum-xzc-3.3.3a2

**Comment by a-bezrukov** [comment] 2019-03-13 06:44
Both latest and the previous 3.0.5a7.

**Comment by ershuev** [comment] 2019-03-13 06:48
I do not know how, but my bug is gone. I can not repeat.

**Comment by blondster** [comment] 2019-03-13 06:50
@ershuev ,
with which version ?

**Comment by ershuev** [comment] 2019-03-13 06:55
tried on
electrum-xzc-3.3.4a1-portable.exe
electrum-xzc-3.3.4a2-portable.exe

**Comment by blondster** [comment] 2019-03-13 08:36
tried on Windows 7 
electrum-xzc-3.3.3a1-portable.exe
and
electrum-xzc-3.3.4a2-portable.exe ,
but problem is the same .
Now downloading VM-Linux and I will try .

**Comment by robin19741806** [comment] 2019-03-13 13:21
> tried on Windows 7
> electrum-xzc-3.3.3a1-portable.exe
> and
> electrum-xzc-3.3.4a2-portable.exe ,
> but problem is the same .
> Now downloading VM-Linux and I will try .

hello, is there any news?

**Comment by robin19741806** [comment] 2019-03-13 13:25
can do a full reset ledger?

**Comment by a-bezrukov** [comment] 2019-03-13 13:32
Yep, it's in Settings -> Device -> Reset All menu

**Comment by blondster** [comment] 2019-03-13 18:46
Hello , 
I tried on a computer with windows 10. With all possible versions of the electrum-xzc, but **without result**. I've noticed that all the computers I've tested have a driver problem. Attaching a photo . Everything I find as a solution - does not help. Is it so? How do I fix it ?
@a-bezrukov -  Is it so? 

![Untitled6](https://user-images.githubusercontent.com/47622428/54305914-ef312400-45d0-11e9-89a2-41b712ca048e.jpg)

**Comment by blondster** [comment] 2019-03-13 18:59
![Untitled7](https://user-images.githubusercontent.com/47622428/54306808-e04b7100-45d2-11e9-9485-874bf14d6073.jpg)

**Comment by Inu-Shiba** [comment] 2019-03-13 21:03
Hello

I found an easy way for urgent cashouts: Recreate a new key with seed words without Ledger.

- Download and install the latest Electrum version (i tryed electrum-xzc-3.3.4a2-portable).
- Run Electrum and click on new/restore if needed.
- Give a new name of your wallet.
- Click on "Standard Wallet", and "Next".
- Click on "I already have a seed", and "Next".
- In the windows "Enter a list of Zcoins addresses or list of private keys", enter all the 24 words used when installing the Ledger the fist time with a space between each word, and click on "Options" button.
- In the little popup window, select "BIP39 seed", an then click OK.
- On the derivation path windows, select "BIP44" and just click "Next".
- Make sure to choose an strong password, because you will not need the Ledger key, then click Next.
- Just wait a wile. 
You can use Electrum without Ledger.
Enjoy.

(Tryed on Windows 7 and Windows 10.)

I was able to send money without my Ledger.
Have a nice day ^^

**Comment by a-bezrukov** [comment] 2019-03-14 04:55
Hi @Inu-Shiba,

This is brilliant! Thank you very much!

**Comment by robin19741806** [comment] 2019-03-14 06:04
Hi @Inu-Shiba,
ohh that's cool! Thank you!

**Comment by blondster** [comment] 2019-03-14 06:16
Hi @Inu-Shiba,
thank you very much !

I still expect some solution with the use of the Ledger wallet .

**Comment by iv41879** [comment] 2019-03-14 20:55
Yes, me too... I am not going to import 12 word seed of my Ledger nowhere

**Comment by Inu-Shiba** [comment] 2019-03-14 23:20
Hello @iv41879 

Yes, i understand... 24 words. These words are used to generate the seed when install the ledger key for the first time.
Obviously these words are randomly generated by the key. This is the reason why we must note these words safely, in the case we loose the password or the Ledger key, because the key will never generate the same secret words again.

If you create a new account in Electrum using the same words in the same order, you will create the same seed as your Leger key, but stored in a wallet file.

When the problem will be solved, i will be able to delete my wallet file from the hard disk, and the seed will not longer be stored somewhere else than in my key.

The money is not stored in the key, but in servers. The seed is used to communicate with the server and identify the account holder. This is the private key used to send money. The public key is used to receive money by everyone. 

Regards.

Inu.

**Comment by iv41879** [comment] 2019-03-15 06:31
@Inu-Shiba, thanks for great overview.  Yes, I understand the principle but no other wallet will ever see 24 word seed of my Ledger device for safety reasons. It just makes Ledger to be less trusted later because we don't know what electrum collects internally. So in my opinion it is just bad practice.

**Comment by robin19741806** [comment] 2019-03-15 15:55
Hi, I performed a full reset Ledger, nothing has changed.

**Comment by robin19741806** [comment] 2019-03-18 05:28
Hi, I do not know how, but I have a transaction, miracles ...

**Comment by blondster** [comment] 2019-03-18 06:16
Hi , confirmed by Ledger wallet ?

**Comment by robin19741806** [comment] 2019-03-18 06:21
Yes, of course, confirmation on Ledger Wallet!

**Comment by blondster** [comment] 2019-03-18 08:04
tonight I will try

**Comment by blondster** [comment] 2019-03-18 17:41
I have updated the version of the Ledger Live. I have updated BitCoin and Zcoin app -1.3.8. And again without success with the transaction confirmation with Ledger :(

**Comment by ToroTer** [comment] 2019-03-19 20:26
I have the same issue. It is not possible to make a confirmation with Ledger . Errors started 2 weeks ago. First  it was sometimes possible, but than no confirmations .

 It was possible sometimes to go to the adress tab and spend from an choosen adress. Parallel there were errors with the wallet and I had to reinstall several timesand got the error "runphyton error or smth like that by the start of the wallet.  I tried many things, but now, when I try to get a confirmation on ledger , I get  an error code or  the wallet freezes and shuts down .

 And sometimes I got the message, that the ledger was not in bitcoinmode .

**Comment by ToroTer** [comment] 2019-03-20 10:37
Last errors were : 
By the first try to get an confirmation message , nothing happened on the ledger . 

And after each second try to get a confirmation or sign message on ledger : 
"bytearrayindex out of range"   , "Exception : Invalid status 6d00" and device not in Bitcoinmode.

**Comment by ToroTer** [comment] 2019-03-22 11:10
Solved the Problem. I did not understand why , but I tried to move coins with rhe znode tool . There I saw that when I had  in the input the adress where I got my mined zcoin ,no confirmation screen  on ledger . So every other adress in Input was possible to spent . When I tried to put only the mining pool receive adress nothing happen. 

So there should be something wrong with this adress?

**Comment by a-bezrukov** [comment] 2019-03-22 11:29
The mined coins should mature 100 blocks since the they were produced. I am testing this case now.

**Comment by ToroTer** [comment] 2019-03-22 17:18
I fixed my problem .
 I had a  zcoin mining pool adress on the Ledger and saw ,
 when I made a transaction all time the mining adress was included in the INPUT, so  no confirmation screen on the Ledger .

 Then I tried it with the Zcoin tool and Ledger. I saw that the problem was only this mining adress . With all other adresses no problems with Ledger .

 I found this articel : https://support.ledger.com/hc/en-us/articles/115005165209-Receive-mining-proceeds

That solved my problem

**Comment by a-bezrukov** [comment] 2019-03-22 17:57
@ToroTer Many thanks for your input!

**Comment by blondster** [comment] 2019-03-22 21:39
I tried also. Forwarded the balance to another address, and then tried to send it from the new address, and then I showed the confirmation message on Ledger Wallet .

**Comment by yuri1313** [comment] 2019-03-23 23:35
> I fixed my problem .
> I had a zcoin mining pool adress on the Ledger and saw ,
> when I made a transaction all time the mining adress was included in the INPUT, so no confirmation screen on the Ledger .
> 
> Then I tried it with the Zcoin tool and Ledger. I saw that the problem was only this mining adress . With all other adresses no problems with Ledger .
> 
> I found this articel : https://support.ledger.com/hc/en-us/articles/115005165209-Receive-mining-proceeds
> 
> That solved my problem

That did it, thank you so much for the input @ToroTer !

**Comment by robin19741806** [comment] 2019-03-25 03:55
ToroTer , thank you so much, the problem is really that.

**Comment by a-bezrukov** [comment] 2019-04-01 11:10
Adding a message which warn about a big number of inputs for a Ledger tx.

**Closed as completed** 2019-04-01 11:11 UTC

**Comment by iv41879** [comment] 2019-06-15 16:30
> I tried also. Forwarded the balance to another address, and then tried to send it from the new address, and then I showed the confirmation message on Ledger Wallet .

Hi, how do you forward the balance to another address without confirmation on Ledger device?

**Comment by a-bezrukov** [comment] 2019-06-15 16:41
@iv41879
You have 2 options - o1 is to chose number of inputs that Ledger can handle, and o2 is to enter the seed words into your Electrum-XZC in BIP44 mode during a new wallet setup. 
o1. My Ledger Nano could handle around 50 inputs, so one could start with showing inputs in View -> Show coins, selecting 50 inputs there and sending it to their address (with min mining fee). Binary search on the proper # of inputs can be done. 
o2 has been perfectly described here: https://github.com/zcoinofficial/electrum-xzc/issues/21#issuecomment-472604529

Good Luck
